In [25]:
import pandas as pd

DATA_PATH = "../data/raw/diabetic_data.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (101766, 50)

In [26]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [27]:
df["readmitted_30"] = (df["readmitted"] == "<30").astype(int)

print("Target created successfully")

Target created successfully

In [28]:
print("Original Target:")
print(df["readmitted"].value_counts())

print("\n30-Day Binary Target:")
print(df["readmitted_30"].value_counts())

print("\n30-Day Binary Target Percentage:")
print(df["readmitted_30"].value_counts(normalize=True) * 100)

Original Target:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

30-Day Binary Target:
readmitted_30
0    90409
1    11357
Name: count, dtype: int64

30-Day Binary Target Percentage:
readmitted_30
0    88.840084
1    11.159916
Name: proportion, dtype: float64

In [29]:
print("Original Target:")
print(df["readmitted"].value_counts())

print("\n30-Day Binary Target:")
print(df["readmitted_30"].value_counts())

print("\n30-Day Binary Target Percentage:")
print(df["readmitted_30"].value_counts(normalize=True) * 100)

Original Target:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

30-Day Binary Target:
readmitted_30
0    90409
1    11357
Name: count, dtype: int64

30-Day Binary Target Percentage:
readmitted_30
0    88.840084
1    11.159916
Name: proportion, dtype: float64

In [30]:
print("Number of columns:", len(df.columns))

print("\nColumns:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Number of columns: 51

Columns:
1. encounter_id
2. patient_nbr
3. race
4. gender
5. age
6. weight
7. admission_type_id
8. discharge_disposition_id
9. admission_source_id
10. time_in_hospital
11. payer_code
12. medical_specialty
13. num_lab_procedures
14. num_procedures
15. num_medications
16. number_outpatient
17. number_emergency
18. number_inpatient
19. diag_1
20. diag_2
21. diag_3
22. number_diagnoses
23. max_glu_serum
24. A1Cresult
25. metformin
26. repaglinide
27. nateglinide
28. chlorpropamide
29. glimepiride
30. acetohexamide
31. glipizide
32. glyburide
33. tolbutamide
34. pioglitazone
35. rosiglitazone
36. acarbose
37. miglitol
38. troglitazone
39. tolazamide
40. examide
41. citoglipton
42. insulin
43. glyburide-metformin
44. glipizide-metformin
45. glimepiride-pioglitazone
46. metformin-rosiglitazone
47. metformin-pioglitazone
48. change
49. diabetesMed
50. readmitted
51. readmitted_30

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 51 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
 50  readmitted_30             101766 non-null  int64
dtypes: int64(14), str(37)
memory usage: 39.6 MB

In [32]:
missing_q = (df == "?").sum().sort_values(ascending=False)

print("Top columns containing '?' values:")
print(missing_q.head(20))

Top columns containing '?' values:
weight               98569
medical_specialty    49949
payer_code           40256
race                  2273
diag_3                1423
diag_2                 358
diag_1                  21
encounter_id             0
tolazamide               0
glyburide                0
tolbutamide              0
pioglitazone             0
rosiglitazone            0
acarbose                 0
miglitol                 0
troglitazone             0
insulin                  0
examide                  0
citoglipton              0
acetohexamide            0
dtype: int64

In [33]:
missing_percentage = (df == "?").mean().sort_values(ascending=False) * 100

print("Top columns by '?' percentage:")
print(missing_percentage.head(20))

Top columns by '?' percentage:
weight               96.858479
medical_specialty    49.082208
payer_code           39.557416
race                  2.233555
diag_3                1.398306
diag_2                0.351787
diag_1                0.020636
encounter_id          0.000000
tolazamide            0.000000
glyburide             0.000000
tolbutamide           0.000000
pioglitazone          0.000000
rosiglitazone         0.000000
acarbose              0.000000
miglitol              0.000000
troglitazone          0.000000
insulin               0.000000
examide               0.000000
citoglipton           0.000000
acetohexamide         0.000000
dtype: float64

In [34]:
print("Duplicate rows:", df.duplicated().sum())

print("Unique encounters:", df["encounter_id"].nunique())

print("Total rows:", len(df))

print("Unique patients:", df["patient_nbr"].nunique())

Duplicate rows: 0
Unique encounters: 101766
Total rows: 101766
Unique patients: 71518

In [35]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
encounter_id,101766.0,NaN,NaN,NaN,165201645.622978,102640295.983457,12522.0,84961194.0,152388987.0,230270887.5,443867222.0
patient_nbr,101766.0,NaN,NaN,NaN,54330400.694947,38696359.346534,135.0,23413221.0,45505143.0,87545949.75,189502619.0
race,101766,6,Caucasian,76099,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,101766,3,Female,54708,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,101766,10,[70-80),26068,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,101766,10,?,98569,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_type_id,101766.0,NaN,NaN,NaN,2.024006,1.445403,1.0,1.0,1.0,3.0,8.0
discharge_disposition_id,101766.0,NaN,NaN,NaN,3.715642,5.280166,1.0,1.0,1.0,4.0,28.0
admission_source_id,101766.0,NaN,NaN,NaN,5.754437,4.064081,1.0,1.0,7.0,7.0,25.0
time_in_hospital,101766.0,NaN,NaN,NaN,4.395987,2.985108,1.0,2.0,4.0,6.0,14.0
payer_code,101766,18,?,40256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
medical_specialty,101766,73,?,49949,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_lab_procedures,101766.0,NaN,NaN,NaN,43.095641,19.674362,1.0,31.0,44.0,57.0,132.0
num_procedures,101766.0,NaN,NaN,NaN,1.33973,1.705807,0.0,0.0,1.0,2.0,6.0
num_medications,101766.0,NaN,NaN,NaN,16.021844,8.127566,1.0,10.0,15.0,20.0,81.0
number_outpatient,101766.0,NaN,NaN,NaN,0.369357,1.267265,0.0,0.0,0.0,0.0,42.0
number_emergency,101766.0,NaN,NaN,NaN,0.197836,0.930472,0.0,0.0,0.0,0.0,76.0
number_inpatient,101766.0,NaN,NaN,NaN,0.635566,1.262863,0.0,0.0,0.0,1.0,21.0
diag_1,101766,717,428,6862,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diag_2,101766,749,276,6752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diag_3,101766,790,250,11555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_diagnoses,101766.0,NaN,NaN,NaN,7.422607,1.9336,1.0,6.0,8.0,9.0,16.0
max_glu_serum,5346,3,Norm,2597,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1Cresult,17018,3,>8,8216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin,101766,4,No,81778,NaN,NaN,NaN,NaN,NaN,NaN,NaN
repaglinide,101766,4,No,100227,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nateglinide,101766,4,No,101063,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chlorpropamide,101766,4,No,101680,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glimepiride,101766,4,No,96575,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acetohexamide,101766,2,No,101765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glipizide,101766,4,No,89080,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glyburide,101766,4,No,91116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tolbutamide,101766,2,No,101743,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pioglitazone,101766,4,No,94438,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rosiglitazone,101766,4,No,95401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acarbose,101766,4,No,101458,NaN,NaN,NaN,NaN,NaN,NaN,NaN
miglitol,101766,4,No,101728,NaN,NaN,NaN,NaN,NaN,NaN,NaN
troglitazone,101766,2,No,101763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tolazamide,101766,3,No,101727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
examide,101766,1,No,101766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citoglipton,101766,1,No,101766,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insulin,101766,4,No,47383,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glyburide-metformin,101766,4,No,101060,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glipizide-metformin,101766,2,No,101753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glimepiride-pioglitazone,101766,2,No,101765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin-rosiglitazone,101766,2,No,101764,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin-pioglitazone,101766,2,No,101765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
change,101766,2,No,54755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diabetesMed,101766,2,Yes,78363,NaN,NaN,NaN,NaN,NaN,NaN,NaN
readmitted,101766,3,NO,54864,NaN,NaN,NaN,NaN,NaN,NaN,NaN
readmitted_30,101766.0,NaN,NaN,NaN,0.111599,0.314874,0.0,0.0,0.0,0.0,1.0

In [36]:
print("===== TARGET DISTRIBUTION =====")

print("\nReadmission counts:")
print(df["readmitted"].value_counts())

print("\nReadmission percentages:")
print(df["readmitted"].value_counts(normalize=True).mul(100).round(2))

===== TARGET DISTRIBUTION =====

Readmission counts:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Readmission percentages:
readmitted
NO     53.91
>30    34.93
<30    11.16
Name: proportion, dtype: float64

In [37]:
print("===== MISSING VALUES =====")

missing_q = (df == "?").sum().sort_values(ascending=False)

missing_q = missing_q[missing_q > 0]

missing_summary = pd.DataFrame({
    "missing_count": missing_q,
    "missing_percentage": (missing_q / len(df) * 100).round(2)
})

missing_summary

===== MISSING VALUES =====

                   missing_count  missing_percentage
weight                     98569               96.86
medical_specialty          49949               49.08
payer_code                 40256               39.56
race                        2273                2.23
diag_3                      1423                1.40
diag_2                       358                0.35
diag_1                        21                0.02

In [38]:
print("===== IDENTIFIERS =====")

print("Total encounters:", len(df))
print("Unique encounters:", df["encounter_id"].nunique())
print("Unique patients:", df["patient_nbr"].nunique())
print("Duplicate rows:", df.duplicated().sum())

===== IDENTIFIERS =====
Total encounters: 101766
Unique encounters: 101766
Unique patients: 71518
Duplicate rows: 0

In [39]:
patient_counts = df["patient_nbr"].value_counts()

print("Patients with multiple encounters:",
      (patient_counts > 1).sum())

print("Maximum encounters for one patient:",
      patient_counts.max())

Patients with multiple encounters: 16773
Maximum encounters for one patient: 40

In [40]:
print("===== DATA TYPES =====")

print(df.dtypes)

===== DATA TYPES =====
encounter_id                int64
patient_nbr                 int64
race                          str
gender                        str
age                           str
weight                        str
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                    str
medical_specialty             str
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                        str
diag_2                        str
diag_3                        str
number_diagnoses            int64
max_glu_serum                 str
A1Cresult                     str
metformin                     str
repaglinide                   str
nateglinide                   str
chlorpropamide                str
glimepiride                   str
acetohexamide                 str
glipizide                     str
glyburide                     str
tolbutamide                   str
pioglitazone                  str
rosiglitazone                 str
acarbose                      str
miglitol                      str
troglitazone                  str
tolazamide                    str
examide                       str
citoglipton                   str
insulin                       str
glyburide-metformin           str
glipizide-metformin           str
glimepiride-pioglitazone      str
metformin-rosiglitazone       str
metformin-pioglitazone        str
change                        str
diabetesMed                   str
readmitted                    str
readmitted_30               int64
dtype: object

In [41]:
print("\n===== DATA TYPE SUMMARY =====")

print(df.dtypes.value_counts())

===== DATA TYPE SUMMARY =====
str      37
int64    14
Name: count, dtype: int64

# Member 2: EDA Review and Feature Analysis

This section extends the initial EDA with demographic distributions, numerical feature distributions, categorical feature review, feature interpretation, and feature relationships with the 30-day readmission target.

In [42]:
demographic_features = ["race", "gender", "age", "weight"]

for col in demographic_features:
    print(f"\n===== {col.upper()} =====")
    print(df[col].value_counts(dropna=False))

===== RACE =====
race
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

===== GENDER =====
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

===== AGE =====
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

===== WEIGHT =====
weight
?            98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

In [43]:
# Numerical feature distributions

numeric_features = [
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses"
]

print("===== NUMERICAL FEATURE SUMMARY =====")
print(df[numeric_features].describe().T)

===== NUMERICAL FEATURE SUMMARY =====
                       count       mean        std  min   25%   50%   75%  \
time_in_hospital    101766.0   4.395987   2.985108  1.0   2.0   4.0   6.0
num_lab_procedures  101766.0  43.095641  19.674362  1.0  31.0  44.0  57.0
num_procedures      101766.0   1.339730   1.705807  0.0   0.0   1.0   2.0
num_medications     101766.0  16.021844   8.127566  1.0  10.0  15.0  20.0
number_outpatient   101766.0   0.369357   1.267265  0.0   0.0   0.0   0.0
number_emergency    101766.0   0.197836   0.930472  0.0   0.0   0.0   0.0
number_inpatient    101766.0   0.635566   1.262863  0.0   0.0   0.0   1.0
number_diagnoses    101766.0   7.422607   1.933600  1.0   6.0   8.0   9.0

                      max
time_in_hospital     14.0
num_lab_procedures  132.0
num_procedures        6.0
num_medications      81.0
number_outpatient    42.0
number_emergency     76.0
number_inpatient     21.0
number_diagnoses     16.0

In [44]:
# Categorical feature review

categorical_features = [
    "race",
    "gender",
    "age",
    "weight",
    "payer_code",
    "medical_specialty",
    "max_glu_serum",
    "A1Cresult",
    "change",
    "diabetesMed"
]

print("===== CATEGORICAL FEATURE REVIEW =====")

for col in categorical_features:
    print(f"\n===== {col.upper()} =====")
    print(df[col].value_counts(dropna=False).head(15))

===== CATEGORICAL FEATURE REVIEW =====

===== RACE =====
race
Caucasian          76099
AfricanAmerican    19210
?                   2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

===== GENDER =====
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

===== AGE =====
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

===== WEIGHT =====
weight
?            98569
[75-100)      1336
[50-75)        897
[100-125)      625
[125-150)      145
[25-50)         97
[0-25)          48
[150-175)       35
[175-200)       11
>200             3
Name: count, dtype: int64

===== PAYER_CODE =====
payer_code
?     40256
MC    32439
HM     6274
SP     5007
BC     4655
MD     3532
CP     2533
UN     2448
CM     1937
OG     1033
PO      592
DM      549
CH      146
WC      135
OT       95
Name: count, dtype: int64

===== MEDICAL_SPECIALTY =====
medical_specialty
?                                  49949
InternalMedicine                   14635
Emergency/Trauma                    7565
Family/GeneralPractice              7440
Cardiology                          5352
Surgery-General                     3099
Nephrology                          1613
Orthopedics                         1400
Orthopedics-Reconstructive          1233
Radiologist                         1140
Pulmonology                          871
Psychiatry                           854
Urology                              685
ObstetricsandGynecology              671
Surgery-Cardiovascular/Thoracic      652
Name: count, dtype: int64

===== MAX_GLU_SERUM =====
max_glu_serum
NaN     96420
Norm     2597
>200     1485
>300     1264
Name: count, dtype: int64

===== A1CRESULT =====
A1Cresult
NaN     84748
>8       8216
Norm     4990
>7       3812
Name: count, dtype: int64

===== CHANGE =====
change
No    54755
Ch    47011
Name: count, dtype: int64

===== DIABETESMED =====
diabetesMed
Yes    78363
No     23403
Name: count, dtype: int64

## Feature Interpretation

The following features were reviewed based on their meaning and potential relevance to 30-day hospital readmission prediction.

| Feature | Meaning / Interpretation | Potential Relevance |
|---|---|---|
| `age` | Patient age group | Demographic risk factor |
| `gender` | Patient gender | Demographic characteristic |
| `race` | Patient race | Demographic characteristic |
| `time_in_hospital` | Length of the current hospital stay | May indicate hospitalization complexity |
| `num_lab_procedures` | Number of laboratory procedures during the encounter | Indicates clinical activity |
| `num_procedures` | Number of procedures during the encounter | Indicates treatment intensity |
| `num_medications` | Number of medications during the encounter | May indicate treatment complexity |
| `number_outpatient` | Number of previous outpatient visits | Indicates prior healthcare utilization |
| `number_emergency` | Number of previous emergency visits | Indicates prior acute healthcare utilization |
| `number_inpatient` | Number of previous inpatient visits | Indicates prior hospitalization history |
| `number_diagnoses` | Number of diagnoses recorded | May indicate clinical complexity |
| `max_glu_serum` | Maximum glucose test result category | May indicate diabetes control |
| `A1Cresult` | HbA1c test result category | May indicate diabetes control |
| `change` | Whether diabetes medications were changed | Indicates treatment changes |
| `diabetesMed` | Whether diabetes medication was prescribed | Indicates diabetes treatment status |

These features are considered potential candidates for further analysis. Final feature selection and preprocessing will be decided during the modeling stage.

In [45]:
# Numerical features vs 30-day readmission

print("===== NUMERICAL FEATURES VS 30-DAY READMISSION =====")

target_summary = df.groupby("readmitted_30")[numeric_features].mean().T

print(target_summary)

===== NUMERICAL FEATURES VS 30-DAY READMISSION =====
readmitted_30               0          1
time_in_hospital     4.349224   4.768249
num_lab_procedures  42.953644  44.226028
num_procedures       1.347123   1.280884
num_medications     15.911137  16.903143
number_outpatient    0.360871   0.436911
number_emergency     0.177803   0.357313
number_inpatient     0.561648   1.224003
number_diagnoses     7.388667   7.692789

In [46]:
print("===== MEDIAN VALUES BY READMISSION STATUS =====")

median_summary = df.groupby("readmitted_30")[numeric_features].median().T

print(median_summary)

===== MEDIAN VALUES BY READMISSION STATUS =====
readmitted_30          0     1
time_in_hospital     4.0   4.0
num_lab_procedures  44.0  45.0
num_procedures       1.0   1.0
num_medications     15.0  16.0
number_outpatient    0.0   0.0
number_emergency     0.0   0.0
number_inpatient     0.0   0.0
number_diagnoses     8.0   9.0

In [47]:
# Demographic features vs 30-day readmission

print("===== AGE VS 30-DAY READMISSION =====")
age_readmission = pd.crosstab(
    df["age"],
    df["readmitted_30"],
    normalize="index"
).round(3)

print(age_readmission)

print("\n===== GENDER VS 30-DAY READMISSION =====")
gender_readmission = pd.crosstab(
    df["gender"],
    df["readmitted_30"],
    normalize="index"
).round(3)

print(gender_readmission)

print("\n===== RACE VS 30-DAY READMISSION =====")
race_readmission = pd.crosstab(
    df["race"],
    df["readmitted_30"],
    normalize="index"
).round(3)

print(race_readmission)

===== AGE VS 30-DAY READMISSION =====
readmitted_30      0      1
age
[0-10)         0.981  0.019
[10-20)        0.942  0.058
[20-30)        0.858  0.142
[30-40)        0.888  0.112
[40-50)        0.894  0.106
[50-60)        0.903  0.097
[60-70)        0.889  0.111
[70-80)        0.882  0.118
[80-90)        0.879  0.121
[90-100)       0.889  0.111

===== GENDER VS 30-DAY READMISSION =====
readmitted_30        0      1
gender
Female           0.888  0.112
Male             0.889  0.111
Unknown/Invalid  1.000  0.000

===== RACE VS 30-DAY READMISSION =====
readmitted_30        0      1
race
?                0.917  0.083
AfricanAmerican  0.888  0.112
Asian            0.899  0.101
Caucasian        0.887  0.113
Hispanic         0.896  0.104
Other            0.904  0.096

## EDA Findings and Feature Observations

### Numerical Features
Patients readmitted within 30 days generally had higher values for:
- Previous inpatient visits
- Previous emergency visits
- Number of medications
- Number of diagnoses
- Time spent in the hospital
- Number of laboratory procedures

The largest difference was observed in `number_inpatient`, suggesting that previous inpatient utilization may be an important predictor of 30-day readmission.

### Demographic Features
Age showed some variation in readmission rates across age groups, while gender showed very little difference between male and female patients.

Race also showed some variation, but the differences were relatively small.

### Potentially Useful Features
Based on this EDA, the following features appear potentially useful for predicting 30-day readmission:

- `number_inpatient`
- `number_emergency`
- `number_outpatient`
- `time_in_hospital`
- `num_medications`
- `number_diagnoses`
- `num_lab_procedures`
- `age`
- `A1Cresult`
- `max_glu_serum`
- `change`
- `diabetesMed`

These are candidate features based on exploratory analysis and should not be considered final feature selections yet.

### Important Considerations
Features should be reviewed based on when the prediction is intended to be made. In particular, variables such as `discharge_disposition_id` may contain information that is only known later in the hospital encounter.

Further preprocessing, encoding, missing-value handling, and final feature selection should be decided as a team before model development.